# Enhanced hotspot configuration with unique IDs for targeted actions
# Each hotspot now has an ID that can be referenced in the UI
# The [[hamptonroads.hotspots]] syntax creates an array automatically

[[hamptonroads.hotspots]]
id = "downtown_shooting"
locality = "Norfolk"
crime_type = "shooting"
center_coords = [36.875, -76.285]
radius = 0.015
base_chance = 0.15
modifiers = ["reputation", "backlash"]
description = "Downtown Shooting Zone"

[[hamptonroads.hotspots]]
id = "waterside_assault"
locality = "Norfolk"
crime_type = "assault"
center_coords = [36.847, -76.293]
radius = 0.012
base_chance = 0.18
modifiers = ["backlash"]
description = "Waterside District Assault Hotspot"

[[hamptonroads.hotspots]]
id = "ghent_petty_theft"
locality = "Norfolk"
crime_type = "petty_theft"
center_coords = [36.866, -76.286]
radius = 0.010
base_chance = 0.22
modifiers = ["reputation"]
description = "Ghent Area Petty Crime"

[[hamptonroads.hotspots]]
id = "ocean_view_vandalism"
locality = "Norfolk"
crime_type = "vandalism"
center_coords = [36.908, -76.272]
radius = 0.018
base_chance = 0.12
modifiers = ["backlash"]
description = "Ocean View Vandalism Zone"

[[hamptonroads.hotspots]]
id = "military_circle_robbery"
locality = "Norfolk"
crime_type = "robbery"
center_coords = [36.888, -76.256]
radius = 0.014
base_chance = 0.10
modifiers = ["reputation", "backlash"]
description = "Military Circle Robbery Hotspot"

[[hamptonroads.hotspots]]
id = "norview_assault"
locality = "Norfolk"
crime_type = "assault"
center_coords = [36.893, -76.279]
radius = 0.016
base_chance = 0.16
modifiers = ["backlash"]
description = "Norview District Assault Zone"

[[hamptonroads.hotspots]]
id = "wards_corner_theft"
locality = "Norfolk"
crime_type = "larceny_auto"
center_coords = [36.882, -76.288]
radius = 0.013
base_chance = 0.20
modifiers = ["reputation"]
description = "Wards Corner Auto Theft Area"

[[hamptonroads.hotspots]]
id = "lambert_point_od"
locality = "Norfolk"
crime_type = "od"
center_coords = [36.857, -76.310]
radius = 0.011
base_chance = 0.08
modifiers = ["reputation", "backlash"]
description = "Lambert's Point Drug Activity"
